networks:
  task-tracker_net:

services:
  app:
    container_name: task-tracker_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9778:9778"
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MY_EMAIL=${MY_EMAIL}
      - MY_PASSWORD=${MY_PASSWORD}
    networks:
      - task-tracker_net

  redis:
    container_name: task-tracker_redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - task-tracker_net